name: deploy

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Kotlin and Gradle
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Run tests
        run: gradle test
  
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Remove container
        run: sudo /usr/bin/docker ps -a --filter "ancestor=speech_to_text_api" -q | xargs -r /usr/bin/docker stop && \
          sudo /usr/bin/docker ps -a --filter "ancestor=speech_to_text_api" -q | xargs -r /usr/bin/docker rm && \
          sudo /usr/bin/docker images -q speech_to_text_api | xargs -r /usr/bin/docker rmi
      - name: Build Docker containers
        run: sudo /usr/bin/docker build -t speech_to_text_api .
      - name: Start Docker containers
        run: sudo /usr/bin/docker run --name SpeechToTextApi -d -p "8082:8080" speech_to_text_api
